### ISSUE TITLE
laravel 5.4兼容

### ISSUE THREAD

**Issue by hsSam** [yuansir/laravel5-rbac-example#11]
这个不做 5.4 的兼容了吗? controll 目录提示 
访问/admin/login
Class App\Http\Controllers\Admin\Auth\LoginController does not exist

**Comment by yuansir** [comment]
@hsSam 不考虑兼容5.4，有时间会开发一个5.4+vue2.0的版本

**Comment by hsSam** [comment]
@yuansir 那能不能修复一下现有的版本，已经报错不能用了。应该是关联依赖的问题。而且少了文件，奇怪， admin/login ,  admin/register 对应的controller 都找不到。我对laravel不是很熟悉，也不清楚是不是我找不对文件的问题。

**Comment by yuansir** [comment]
@hsSam  我试了一下并没有任何问题，而且

> admin/login , admin/register 对应的controller 都找不到

请自己好好看下Laravel的文档和API文档，看下Auth部分的源码，登录和注册的路由在哪里定义的，有问题请直接邮件给我
