### ISSUE TITLE
数据库没有user_role表

### ISSUE THREAD

**Issue by xieqx1991** [yuansir/laravel5-rbac-example#12]
![0379c6cf-afee-4d18-8532-f7a100cc7fa0](https://cloud.githubusercontent.com/assets/8676463/23444493/6f3679a2-fe70-11e6-93f4-7d6ab421caf0.JPG)
![qq 20170301111412](https://cloud.githubusercontent.com/assets/8676463/23444492/6f34b4f0-fe70-11e6-9ae8-63bb0ecc773d.jpg)

错误如图，按照readme操作，登录后台点击用户权限时报错

**Comment by yuansir** [comment]
Laravel的版本？执行过seed了吗？

Ryan


开 2017年3月1日 在 上午11:16:56, Hsieh (notifications@github.com<mailto:notifications@github.com>) 写到:

[0379c6cf-afee-4d18-8532-f7a100cc7fa0]<https://cloud.githubusercontent.com/assets/8676463/23444493/6f3679a2-fe70-11e6-93f4-7d6ab421caf0.JPG>
[qq 20170301111412]<https://cloud.githubusercontent.com/assets/8676463/23444492/6f34b4f0-fe70-11e6-9ae8-63bb0ecc773d.jpg>

错误如图，按照readme操作，登录后台点击用户权限时报错

**Comment by xieqx1991** [comment]
版本5.2.45，readme都执行了，后台能进入
![image](https://cloud.githubusercontent.com/assets/8676463/23444605/250fb7ac-fe71-11e6-987e-394c49607640.png)

**Comment by yuansir** [comment]
@BoomThanks 
更新一下，配置文件更新了一下
```
  'role_user_table' => 'admin_user_role',
  'reign_key' => 'admin_user_id',
```
