### ISSUE TITLE
composer install不了

### ISSUE THREAD

**Issue by Ystars** [yuansir/laravel5-rbac-example#14]
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Package operations: 33 installs, 0 updates, 0 removals
  - Installing illuminate/pipeline (v5.2.43): Downloading (failed)    Failed to download illuminate/pipeline from dist: The "https://packagist.phpcomposer.com/files/illuminate/pipeline/592d84b101437de3432851e4fa60a33f849164e5.zip" file could not be downloaded (HTTP/1.1 404 Not Found)

**Comment by yuansir** [comment]
删除
compose.lock 重新安装

**Comment by Ystars** [comment]
重新安装执行 php artisan db:seed 只有导入admin_password_resets和password_resets这两表其他都没有导入
