### ISSUE TITLE
composer install超时

### ISSUE THREAD

**Issue by ghost** [yuansir/laravel5-rbac-example#4]
```
Downloading: Connecting...    Downloading: Connecting...    Downloading: Connecting...    Failed to download doctrine/common from dist: Your configuration does not allow connections to http://packagist.phpcomposer.com/files/doctrine/common/a579557bc689580c19fee4e27487a67fe60defc0.zip. See https://getcomposer.org/doc/06-config.md#secure-http for details.
Now trying to download from source
```
- Installing doctrine/common (v2.6.1)
  Cloning a579557bc689580c19fee4e27487a67fe60defc0
  
  [Symfony\Component\Process\Exception\ProcessTimedOutException]
  The process "git clone --no-checkout 'https://github.com/doctrine/common.gi
  t' '/Users/qk/Code/laravel5-rbac-example/vendor/doctrine/common' && cd '/Us
  ers/qk/Code/laravel5-rbac-example/vendor/doctrine/common' && git remote add
  composer 'https://github.com/doctrine/common.git' && git fetch composer" e
  xceeded the timeout of 300 seconds.

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...

**Comment by yuansir** [comment]
我试了下没有问题，用代理，或者说你代理有问题，试试 http://pkg.phpcomposer.com/

**Comment by cnyoungman** [comment]
Installing psy/psysh (v0.6.1)
    Downloading: Connecting...    Downloading: Connecting...    Downloading: Connecting...    Failed to download psy/psysh from dist: Your configuration does not allow connections to http://packagist.phpcomposer.com/files/bobthecow/psysh/0f04df0b23663799a8941fae13cd8e6299bde3ed.zip. See https://getcomposer.org/doc/06-config.md#secure-http for details.
    Now trying to download from source
- Installing psy/psysh (v0.6.1)
  Cloning 0f04df0b23663799a8941fae13cd8e6299bde3ed
  
  [Symfony\Component\Process\Exception\ProcessTimedOutException]
  The process "git clone --no-checkout "https://github.com/bobthecow/psysh.gi
  t" "E:\www\blog\vendor\psy\psysh" && cd /D "E:\www\blog\vendor\psy\psysh" &
  & git remote add composer "https://github.com/bobthecow/psysh.git" && git f
  etch composer" exceeded the timeout of 300 seconds.

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...

我install 的时候超时  使用代理页一样， 亲 这是因为啥啊

**Comment by u0hz** [comment]
composer要求使用https
修改 composer 的全局配置文件（推荐方式）
打开命令行窗口（windows用户）或控制台（Linux、Mac 用户）并执行如下命令：
`composer config -g repo.packagist composer https://packagist.phpcomposer.com`

OR

composer.json  ->  config  ->  "secure-http": false
