### ISSUE TITLE
新添加的测试狗用户权限没生效

### ISSUE THREAD

**Issue by akgitcom** [yuansir/laravel5-rbac-example#5]
左边的菜单显示不正确，没有权限的也显示出来了

**Comment by yuansir** [comment]
admin@admin.com 是超级管理员用户，默认显示所有权限 @akgitcom

**Comment by akgitcom** [comment]
好了，# 不能都用这个有点区别就好
退出登录后访问链接报错：

ErrorException in AuthenticateAdmin.php line 28:
Trying to get property of non-object

加了判断好了。
