### ISSUE TITLE
Failed to download *** from dist: Your configuration does not allow

### ISSUE THREAD

**Issue by includeleec** [yuansir/laravel5-rbac-example#6]
Failed to download jakub-onderka/php-console-color from dist: Your configuration does not allow connections to http://packagist.phpcomposer.com/files/JakubOnderka/PHP-Console-Color/e0b393dacf7703fc36a4efc3df1435485197e6c1.zip. See https://getcomposer.org/doc/06-config.md#secure-http for details.
    Now trying to download from source

**Comment by huchiwen** [comment]
我遇到和你一样的问题~

**Comment by zqq707297386** [comment]
我也是遇到这样的问题。该如何解决呢
