### ISSUE TITLE
Request类里面的messgae()自定义错误消息如何实现？

### ISSUE THREAD

**Issue by chris-fung** [yuansir/laravel5-rbac-example#7]
如题，admin的Reques基类引用Validation会报错？

**Comment by whossun** [comment]
Validation 一般在控制器中使用，而 基类中引用了Validation是为了自定义错误显示格式的，
一般的request类常定义authorize， rules， 而messages定义返回信息的内容

**Comment by yuansir** [comment]
@chris-fung @whossun 先关了，有laravel使用的问题可以邮件交流，程序bug欢迎提issue
